[theme]
primaryColor="#697565"
backgroundColor="#181C14"
secondaryBackgroundColor="#3C3D37"
textColor="#ECDFCC"

#primaryColor="#629584"
#backgroundColor="#243642"
#secondaryBackgroundColor="#387478"
#textColor="#E2F1E7"